services:
  mongo_container:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc1235
    volumes:
      - mongo_data_container:/data/db
volumes:
 mongo_data_container:



